sudo: required
language: generic

services:
  - docker

before_install:
  - docker build -t clive1234/docker-react -f Dockerfile.dev .

script:
  - docker run -e CI=true clive1234/docker-react npm run test -- --coverage
